  altura_tampo_imprimir = ALTURA_TAMPO_IMPRIMIR / APPTAMPO;
  altura_tampo_entintar = ALTURA_TAMPO_ENTINTAR / APPTAMPO;
  distancia_carro_imprimir = DISTANCIA_CARRO_IMPRIMIR / APPCARRO;
  distancia_carro_entintar = DISTANCIA_CARRO_ENTINTAR / APPCARRO;
  posicion_cuchilla_arriba = POSICION_CUCHILLA_ARRIBA / APPCUCHILLA;
  posicion_cuchilla_abajo = POSICION_CUCHILLA_ABAJO / APPCUCHILLA;
  inicio_barrido = INICIO_BARRIDO / APPCARRO;
  fin_barrido = FIN_BARRIDO / APPCARRO;
  presionimprimir = PRESIONIMPRIMIR / APPTAMPO;
  presionentintar = PRESIONENTINTAR / APPTAMPO;
  ancho = ANCHO / APPCARRO;
  Serial.println("Variables recalculadas");
  float ALTURA_TAMPO_IMPRIMIR = 30;
float ALTURA_TAMPO_ENTINTAR = 30;
float DISTANCIA_CARRO_IMPRIMIR = 60;
float DISTANCIA_CARRO_ENTINTAR = 160;
float POSICION_CUCHILLA_ARRIBA = 1;//De 0 a 100, 0 lo mas arriba
//, 100 lo mas abajo, máximo m vueltas
float POSICION_CUCHILLA_ABAJO = 50;
float INICIO_BARRIDO = 20;
float FIN_BARRIDO = 90;
float PRESIONIMPRIMIR = 20;
float PRESIONENTINTAR = 20;
float ANCHO = 70;
int ciclos_tampo = 20;
int ciclos_carro = 25;
int ciclos_cuchilla = 30;
double APPCARRO = 0.046;
double APPTAMPO = 0.025;
double APPCUCHILLA = 0.025;
double MAX = 230 / APPCARRO;

    ALTURA_TAMPO_IMPRIMIR = EEPROM.read(1);
  ALTURA_TAMPO_ENTINTAR = EEPROM.read(2);
  DISTANCIA_CARRO_IMPRIMIR = EEPROM.read(3);
  DISTANCIA_CARRO_ENTINTAR = EEPROM.read(4);
  POSICION_CUCHILLA_ARRIBA = EEPROM.read(5);
  POSICION_CUCHILLA_ABAJO = EEPROM.read(6);
  INICIO_BARRIDO = EEPROM.read(7);
  FIN_BARRIDO = EEPROM.read(8);
  PRESIONIMPRIMIR = EEPROM.read(9);
  PRESIONENTINTAR = EEPROM.read(10);
  ANCHO = EEPROM.read(11);
  ciclos_tampo = EEPROM.read(12);
  ciclos_carro = EEPROM.read(13);
  ciclos_cuchilla = EEPROM.read(14);

 CalcularVariables();
          ReiniciarTampo();
          ReiniciarCarro();
          ReiniciarCuchilla();
          AvanceCarroACC(MAX);
          delay(500);
          RetroCarro(distancia_carro_imprimir);
          delay(500);
          RetroCarro(inicio_barrido);
          delay(500);
          CerrarCuchilla(posicion_cuchilla_abajo - posicion_cuchilla_arriba);
          delay(500);
          RetroCarroACC(fin_barrido - inicio_barrido);
          delay(500);
          AbrirCuchilla(posicion_cuchilla_abajo - posicion_cuchilla_arriba);
          delay(500);
          ReiniciarCarro();
          ReiniciarCuchilla();
          myNextion.setComponentValue("bt0", 0);
